### PR TITLE
- Uses regex to pull date from scraped data.

### PR DESCRIPTION
**Pull request by quetzaluz**
@salazareddie -- I realize this may not be an ideal approach, but it fixes the case posted in issue #5

### CODE REVIEW

**Comment by salazareddie** [comment]
@quetzaluz Seems fine. Can't think of a better solution.

**Comment by quetzaluz** [comment]
OK, thanks for review. Will handle merging (maybe list myself as a contributor in the gem file if that's ok.

**Comment by salazareddie** [comment]
K, sounds good!

**Comment by salazareddie** [comment]
Make sure to bump the version

**Comment by quetzaluz** [comment]
thanks for the reminder :+1:

**Comment by quetzaluz** [comment]
bumped version, squashed, and merged. Closing.

**Pull request closed without merging**
